### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by RickCogley** [neatnik/salty#1]
This seems like a great way to share passwords with clients. You can email the encrypted short text and tell them the key over the phone. 

About implementation, I wonder, could you share how you implemented on salty.fyi? I would like to put it on our own server (we would need the UI to be Japanese), but want to understand how you've got it set up, if you don't mind. For instance, the form action is pointing at `/#salty` but what does that mean on the server's file system? 

```
<form action="/#salty" method="post">

<label for="payload">Payload</label>
<p><textarea name="payload" id="payload">Quick brown fox</textarea></p>

<label for="key">Key</label>
<p><input type="text" name="key" id="key" value="123"></p>

<input type="submit" value="Go">

</form>
```

**Comment by newbold** [comment]
I went ahead and uploaded the code for the [site itself](https://github.com/neatnik/salty/tree/master/salty.fyi), and you can see how I implemented it in the [index.php](https://github.com/neatnik/salty/blob/master/salty.fyi/index.php) script.

The form action is a bit misleading; it's really the same as `"/"` which is the site index itself, and the `#salty` anchor is just a way to get the browser to jump down to the relevant stuff when the form is submitted. Nothing overly fancy going on there!

**Comment by RickCogley** [comment]
Thanks!

**Comment by RickCogley** [comment]
Also, you can pre-populate the payload using an URL param like: 

```
https://salty.fyi/index.php?payload=f6f6f6f6f6f6f6f6f6f
```

... so long as the payload has been url encoded. It will populate the payload form field, and you can then easily just say "lets talk on the phone and I will tell you the key".

**Comment by sorrynofocus** [comment]
Pretty neat encryption - enjoyed the stenography site.

**Comment by d-a-s-h-o** [comment]
> I went ahead and uploaded the code for the [site itself](https://github.com/neatnik/salty/tree/master/salty.fyi), and you can see how I implemented it in the [index.php](https://github.com/neatnik/salty/blob/master/salty.fyi/index.php) script.
> 
> The form action is a bit misleading; it's really the same as `"/"` which is the site index itself, and the `#salty` anchor is just a way to get the browser to jump down to the relevant stuff when the form is submitted. Nothing overly fancy going on there!

Can you upload this again. I'm not sure how to structure the form to return the ciphers or the compressed version of the data. This would be really great to implement as a security tool with a custom salt. Thanks :)

**Comment by newbold** [comment]
Sorry about that, @d-a-s-h-o — not sure why I removed that previously. It's back now, [located here](https://github.com/neatnik/salty/blob/main/site/index.php). Let me know if you have any questions about the implementation.

**Comment by d-a-s-h-o** [comment]
Ah perfect. Got it working now. Thanks for uploading again :) Great service btw
