### ISSUE TITLE
Translation of UI, result on correct page

### ISSUE THREAD

**Issue by RickCogley** [neatnik/salty#4]
Hi - I'm trying to have two salty `index.php` pages, one in English and the other in Japanese. 

Japanese would be: 

https://mydomain.com/index.php (or of course https://mydomain.com)

English would be: 

https://mydomain.com/en/

I am referencing `salty.php` on `/en/index.php` at `../salty.php` and things seem to be working, but, if I enter a payload and key on `/en/index.php`, the result comes out at `/index.php#salty` showing the result on the Japanese page. I'd like this to be piped into the English index.php.

What can I do to make the result display in the right language's page?

**Comment by RickCogley** [comment]
Ah, nevermind, found it. The form action has to include the language URL. Just edit on the appropriate language page, like this for English: 

`<form action="/en/#salty" method="post">`

**Comment by newbold** [comment]
Glad you got it! I was just about to ask some clarifying questions. 👍
